# Generated by Django 5.0.4 on 2024-09-20 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Phone number must be exactly 9 digits.')])),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Applicant'), (2, 'Employer'), (0, 'Admin')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
