# Generated by Django 5.0.4 on 2024-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[('Applicant', 'Applicant'), ('Employer', 'Employer'), ('Admin', 'Admin')]),
        ),
    ]
