# Generated by Django 5.0.4 on 2024-09-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Employer', 'Employer'), ('Admin', 'Admin')], max_length=9),
        ),
    ]
